package com.pemex.logistica.censos.dto;
import lombok.Data;

@Data
public class TransporteDuctoDTO {
    private Integer id_transporte_ducto;
    private String nombre_transporte_ducto;
    private Integer id_subdireccion_logistica;
    private Integer id_entidad_federativa;
    private Integer id_direccion;
    private Integer id_gerencia;

    // Getters and Setters can be generated by Lombok or manually added if needed
}
